### ISSUE TITLE
Disable CLAP build option.

### ISSUE THREAD

**Issue by ghost** [cvde/RoomReverb#2]
Please add command to disable CLAP build. RPi users can't use CLAP and also can't build RoomReverb caused by `cmake_minimum_required`.

**Comment by cvde** [comment]
Hi!

I assume by "RPi" you mean Raspberry Pi?
Unfortunately, I have no way to test the plugin itself or the build process on a Raspberry Pi.

However, by commenting out the following section in CMakeLists.txt, you can disable the CLAP build:

```
clap_juce_extensions_plugin(
    TARGET ${PROJECT_NAME}
    CLAP_ID "com.elephantdsp.roomreverb"
    CLAP_FEATURES audio-effect reverb
)
```

No idea what's the problem with `cmake_minimum_required` - but feel free to send me a Raspberry Pi ;)

**Comment by ghost** [comment]
Yes, Raspsberry Pi. `cmake_minimum_required` only occurs when building CLAP because RPi cmake version is 18.x.

However, to disable the CLAP by commenting also need `add_subdirectory(Libs/clap-juce-extensions EXCLUDE_FROM_ALL)`.

Can I open PR for add disable CLAP build command option? **By the default it is ON**, for peoples who do not need CLAP like me,  they can turn off CLAP build simply using command.

**Comment by ghost** [comment]
I opened PR for this, please check it.

**Comment by cvde** [comment]
Thanks for your PR! I guess I understood the problem now.

I would consider this a bug... I require CMake 3.15, but then need CMake 3.21 to build the CLAP version. The obvious solution, of course, would be for me to also require CMake 3.21.

However, to keep support for the Raspberry Pi, I implemented a CMake version check so that the CLAP version will not be built if the CMake version is below 3.21.

I hope this approach works for you!

**Comment by ghost** [comment]
Thank you for your work. It works perfectly :)
